az-configuration:
- name: az1
  iaas_configuration_name: haas-242
  clusters:
  - cluster: Cluster
    host_group: null
    resource_pool: pas-az1
- name: az2
  iaas_configuration_name: haas-242
  clusters:
  - cluster: Cluster
    host_group: null
    resource_pool: pas-az2
- name: az3
  iaas_configuration_name: haas-242
  clusters:
  - cluster: Cluster
    host_group: null
    resource_pool: pas-az3
iaas-configurations:
- additional_cloud_properties: {}
  bosh_disk_path: pcf_disk
  bosh_template_folder: pcf_templates
  bosh_vm_folder: pcf_vms
  datacenter: Datacenter
  disk_type: thin
  ephemeral_datastores_string: LUN01
  name: default
  nsx_address: nsxmgr-01.haas-242.pez.pivotal.io
  nsx_ca_certificate: ((nsx_ca_cert.certificate))
  nsx_mode: nsx-t
  nsx_networking_enabled: true
  nsx_username: admin
  nsx_password: ((nsx_password))
  persistent_datastores_string: LUN01
  ssl_verification_enabled: false
  vcenter_host: vcsa-01.haas-242.pez.pivotal.io
  vcenter_username: Administrator@vsphere.local
  vcenter_password: ((vcenter_password))
network-assignment:
  network:
    name: infrastructure
  other_availability_zones: []
  singleton_availability_zone:
    name: az1
networks-configuration:
  icmp_checks_enabled: false
  networks:
  - name: infrastructure
    subnets:
    - iaas_identifier: PAS-Infrastructure
      cidr: 192.168.1.0/24
      dns: 10.192.2.10
      gateway: 192.168.1.1
      reserved_ip_ranges: 192.168.1.1-192.168.1.10
      availability_zone_names:
      - az1
      - az2
      - az3
  - name: pas
    subnets:
    - iaas_identifier: PAS-Deployment
      cidr: 192.168.2.0/24
      dns: 10.192.2.10
      gateway: 192.168.2.1
      reserved_ip_ranges: ""
      availability_zone_names:
      - az1
      - az2
      - az3
  - name: services
    subnets:
    - iaas_identifier: PAS-Services
      cidr: 192.168.3.0/24
      dns: 10.192.2.10
      gateway: 192.168.3.1
      reserved_ip_ranges: ""
      availability_zone_names:
      - az1
      - az2
      - az3
properties-configuration:
  director_configuration:
    blobstore_type: local
    bosh_recreate_on_next_deploy: false
    bosh_recreate_persistent_disks_on_next_deploy: false
    database_type: internal
    director_worker_count: 5
    encryption:
      keys: []
      providers: []
    hm_emailer_options:
      enabled: false
    hm_pager_duty_options:
      enabled: false
    identification_tags: {}
    job_configuration_on_tmpfs: false
    keep_unreachable_vms: false
    local_blobstore_options:
      tls_enabled: true
    ntp_servers_string: time.svc.pivotal.io
    post_deploy_enabled: false
    resurrector_enabled: false
    retry_bosh_deploys: true
    skip_director_drain: false
  dns_configuration:
    excluded_recursors: []
    handlers: []
  security_configuration:
    opsmanager_root_ca_trusted_certs: true
    trusted_certificates: ((my_ca.certificate))
    generate_vm_passwords: true
  syslog_configuration:
    enabled: false
resource-configuration:
  compilation:
    additional_networks: []
    additional_vm_extensions: []
    instance_type:
      id: automatic
    instances: automatic
    nsx:
      lbs: []
      security_groups: []
    nsxt:
      lb:
        server_pools: []
      ns_groups: []
    swap_as_percent_of_memory_size: automatic
  director:
    additional_networks: []
    additional_vm_extensions: []
    instance_type:
      id: automatic
    instances: automatic
    nsx:
      lbs: []
      security_groups: []
    nsxt:
      lb:
        server_pools: []
      ns_groups: []
    persistent_disk:
      size_mb: automatic
    swap_as_percent_of_memory_size: automatic
vmextensions-configuration: 
- name: router-extension
  cloud_properties:
    nsxt:
      lb:
        server_pools:
        - name: PAS-GoRouter443ServerPool
          port: 443
vmtypes-configuration: {}
